version = 0.1

# =============================================================================
# Development Environment (uses QA template for development)
# =============================================================================
[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "ap-northeast-1"
stack_name = "dev-zuora-event-handler"
template_file = "template.yaml"
parameter_overrides = "Env=\"dev\""

# =============================================================================
# QA Environment
# =============================================================================
[qa.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false  # Auto-deploy for QA
resolve_s3 = true
region = "ap-northeast-1"
stack_name = "qa-zuora-event-handler"
template_file = "template.yaml"
parameter_overrides = "Env=\"qa\""

# =============================================================================
# Production Environment
# =============================================================================
[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true  # Require manual approval for production
resolve_s3 = true
region = "ap-northeast-1"
stack_name = "prod-zuora-event-handler"
template_file = "template.prod.yaml"
parameter_overrides = "Env=\"prod\""

# =============================================================================
# Default (same as dev)
# =============================================================================
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "ap-northeast-1"
stack_name = "dev-zuora-event-handler"
template_file = "template.yaml"
parameter_overrides = "Env=\"dev\""
