AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Zuora Event Handler - Production Environment

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Parameters:
  Env:
    Type: String
    Description: Deployment environment name
    Default: "prod"

Resources:
  ZuoraEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}-zuora-event-handler"
      CodeUri: ZuoraEventHandler/
      Handler: com.fujifilm.fb.spf.subscription.zuora.complement.ZuoraEventHandlerApp::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18"
      Environment:
        Variables:
          ZUORA_API_SECRET: "prod/zuora/apis"
          ZUORA_ENDPOINT: "https://rest.zuora.com/v1/"
          LOG_LEVEL: "WARN"
          ENV: !Ref Env
          # SSL/TLS settings for Zuora SDK (OkHttp)
          JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStore=/opt/java/openjdk/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.keyStore=/opt/java/openjdk/lib/security/cacerts -Djavax.net.ssl.keyStorePassword=changeit"
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/zuora/apis*"
          - Effect: Allow
            Action:
              - lambda:GetLayerVersion
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18"
      Tags:
        Environment: !Ref Env
        Project: "ZuoraEventHandler"
        ManagedBy: "SAM"

Outputs:
  ZuoraEventHandler:
    Description: "Zuora Event Handler Lambda Function ARN"
    Value: !GetAtt ZuoraEventHandler.Arn
