AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Zuora Event Handler

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Parameters:
  Env:
    Type: String
    Description: Deployment environment name (e.g., qa, prod)

Resources:
  ZuoraEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}-zuora-event-handler"
      CodeUri: ZuoraEventHandler/
      Handler: com.fujifilm.fb.spf.subscription.zuora.complement.ZuoraEventHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      Environment:
        Variables:
          ZUORA_CLIENT_ID: "your-client-id"
          ZUORA_CLIENT_SECRET_PARAM: "/zuora-event-handler/sbx3/client-secret"
          ZUORA_ENDPOINT: "https://rest.apisandbox.zuora.com/v1/"
      Events:
        ZuoraEvent:
          Type: Api
          Properties:
            Path: /zuora-event
            Method: post

Outputs:
  ZuoraEventHandlerApi:
    Description: "API Gateway endpoint URL for Zuora Event Handler"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/zuora-event/"

  ZuoraEventHandler:
    Description: "Zuora Event Handler Lambda Function ARN"
    Value: !GetAtt ZuoraEventHandler.Arn

  ZuoraEventHandlerIamRole:
    Description: "Implicit IAM Role created for Zuora Event Handler function"
    Value: !GetAtt ZuoraEventHandlerRole.Arn
