AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Zuora Event Handler

Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Parameters:
  Env:
    Type: String
    Description: Deployment environment name (e.g., qa, prod)

Resources:
  ZuoraEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}-zuora-event-handler"
      CodeUri: ZuoraEventHandler/
      Handler: com.fujifilm.fb.spf.subscription.zuora.complement.ZuoraEventHandlerApp::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      Layers:
        - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18
      Environment:
        Variables:
          ZUORA_CLIENT_ID: "your-client-id"
          ZUORA_API_SECRET: "qa/zuora/apis"
          ZUORA_ENDPOINT: "https://rest.apisandbox.zuora.com/v1/"
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:ap-northeast-1:482206272043:secret:qa/zuora/apis-9BPW5E
          - Effect: Allow
            Action:
              - lambda:GetLayerVersion
            Resource: arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:18

Outputs:
  ZuoraEventHandler:
    Description: "Zuora Event Handler Lambda Function ARN"
    Value: !GetAtt ZuoraEventHandler.Arn
